version: '3'

services:
    backend_party:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/backend/development.Dockerfile
        entrypoint: /app/docker/backend/wsgi-entrypoint.sh
        image: django_backend_party
        working_dir: /app/backend
        depends_on:
            - postgres
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        env_file:
            - ./.envs/.django
            - ./.envs/.postgres

    frontend:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/frontend/development.Dockerfile
        image: react_frontend_party
        depends_on:
            - backend_party
        volumes:
            - ./frontend/src:/app/frontend/src
            - ./frontend/public:/app/frontend/public
        ports:
            - "3000:3000"
        environment:
            - WATCHPACK_POLLING=true
            - WDS_SOCKET_PORT=3000
            - REACT_APP_BACKEND_ADDRESS=http://localhost:8000
            - PUBLIC_URL=/app

    postgres:
        build:
            context: .
            dockerfile: ./docker/postgres/Dockerfile
        image: postgres_db_party_backend
        volumes:
            - postgres_party_volume:/var/lib/postgresql/data
            - postgres_party_volume_backups:/backups
        env_file:
            - ./.envs/.postgres

volumes:
    postgres_party_volume: {}
    postgres_party_volume_backups: {}
