"""
Management command to import Posadas Party data from a Demozoo JSON file.

Usage:
    python manage.py import_demozoo posadas_demozoo.json [--dry-run] [--skip-existing] [--download-screenshots]

Creates editions, compos, HasCompo links, and productions from scraped data.
Skips editions that already exist (matched by title).
"""

import json
import logging
import time
from datetime import date, datetime
from urllib.request import urlopen, Request
from urllib.error import URLError

from django.core.management.base import BaseCommand
from django.core.files.base import ContentFile
from django.contrib.auth import get_user_model
from django.db import transaction
from django.utils import timezone

from dpms.compos.models import Edition, Compo, HasCompo, Production

User = get_user_model()
logger = logging.getLogger(__name__)

# Demozoo platform name -> DPMS platform choice
PLATFORM_MAP = {
    "Amiga OCS/ECS": "amiga_ocs",
    "Amiga AGA": "amiga_aga",
    "Amiga PPC/RTG": "amiga_aga",
    "Windows": "pc",
    "Linux": "pc",
    "MS-Dos": "pc",
    "Mac OS X": "pc",
    "Commodore 64": "c64",
    "Atari ST/STE": "atari_st",
    "ZX Spectrum": "zx_spectrum",
    "MSX": "msx",
    "Amstrad CPC": "amstrad_cpc",
    "SNES/Super Famicom": "snes",
    "Sega Master System": "megadrive",
    "Sega Mega Drive/Genesis": "megadrive",
    "Game Boy": "gameboy",
    "Game Boy Advance": "gameboy",
    "Arduino": "arduino",
    "JavaScript": "web",
    "Browser": "web",
    "PICO-8": "other",
    "TIC-80": "other",
    "VIC-20": "other",
    "Android": "other",
    "Custom Hardware": "other",
}


class Command(BaseCommand):
    help = "Import Posadas Party data from Demozoo JSON file"

    def add_arguments(self, parser):
        parser.add_argument(
            "json_file",
            help="Path to the JSON file generated by scrape_demozoo",
        )
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Show what would be imported without making changes",
        )
        parser.add_argument(
            "--download-screenshots",
            action="store_true",
            help="Download screenshots from Demozoo",
        )
        parser.add_argument(
            "--admin-email",
            default=None,
            help="Email of admin user to assign as owner (default: first superuser)",
        )

    def get_admin_user(self, email=None):
        if email:
            try:
                return User.objects.get(email=email)
            except User.DoesNotExist:
                self.stderr.write(self.style.ERROR(f"User {email} not found"))
                return None

        admin = User.objects.filter(is_superuser=True).first()
        if not admin:
            admin = User.objects.first()
        return admin

    def download_screenshot(self, url, retries=3):
        for attempt in range(retries):
            try:
                req = Request(url, headers={"User-Agent": "DPMS/1.0"})
                resp = urlopen(req, timeout=15)
                content = resp.read()
                filename = url.rsplit("/", 1)[-1]
                return filename, content
            except (URLError, OSError) as e:
                if attempt < retries - 1:
                    time.sleep(2 * (attempt + 1))
        return None

    def parse_date(self, date_str):
        if not date_str:
            return None
        try:
            parts = date_str.split("-")
            if len(parts) == 3:
                return date(int(parts[0]), int(parts[1]), int(parts[2]))
            elif len(parts) == 2:
                return date(int(parts[0]), int(parts[1]), 1)
            elif len(parts) == 1:
                return date(int(parts[0]), 1, 1)
        except (ValueError, IndexError):
            pass
        return None

    def map_platform(self, platforms):
        for p in platforms:
            mapped = PLATFORM_MAP.get(p)
            if mapped:
                return mapped
        return "other" if platforms else ""

    def edition_exists(self, name):
        """Check if an edition with a similar name already exists."""
        # Normalize: "Posadas 2025" matches "Posadas Party 2025"
        # Check exact match first, then try with/without "Party"
        if Edition.objects.filter(title__iexact=name).exists():
            return True
        # "Posadas 2025" -> also check "Posadas Party 2025"
        if "Party" not in name:
            with_party = name.replace("Posadas", "Posadas Party", 1)
            if Edition.objects.filter(title__iexact=with_party).exists():
                return True
        # "Posadas Party 2025" -> also check "Posadas 2025"
        without_party = name.replace("Posadas Party ", "Posadas ")
        if Edition.objects.filter(title__iexact=without_party).exists():
            return True
        return False

    def handle(self, *args, **options):
        json_file = options["json_file"]
        dry_run = options["dry_run"]
        download_screenshots = options["download_screenshots"]

        with open(json_file, "r", encoding="utf-8") as f:
            editions_data = json.load(f)

        admin_user = self.get_admin_user(options.get("admin_email"))
        if not admin_user:
            self.stderr.write(self.style.ERROR("No admin user found. Create one first."))
            return

        self.stdout.write(f"Admin user: {admin_user.email}")
        self.stdout.write(f"Editions in file: {len(editions_data)}")

        if dry_run:
            self.stdout.write(self.style.WARNING("DRY RUN - no changes will be made"))

        stats = {
            "editions_created": 0,
            "editions_skipped": 0,
            "compos_created": 0,
            "compos_reused": 0,
            "hascompos_created": 0,
            "productions_created": 0,
            "screenshots_downloaded": 0,
        }

        for ed_data in editions_data:
            name = ed_data["name"]
            self.stdout.write(f"\n{'='*50}")
            self.stdout.write(self.style.SUCCESS(f"Edition: {name}"))

            # Check if edition already exists
            if self.edition_exists(name):
                self.stdout.write(self.style.WARNING(f"  SKIPPED: '{name}' already exists"))
                stats["editions_skipped"] += 1
                continue

            if dry_run:
                total = sum(len(c["productions"]) for c in ed_data["competitions"])
                self.stdout.write(f"  Would create: {len(ed_data['competitions'])} compos, {total} productions")
                stats["editions_created"] += 1
                continue

            # Parse dates
            start_date = self.parse_date(ed_data.get("start_date"))
            end_date = self.parse_date(ed_data.get("end_date"))

            start_dt = timezone.make_aware(
                datetime.combine(start_date, datetime.min.time())
            ) if start_date else timezone.now()

            end_dt = timezone.make_aware(
                datetime.combine(end_date, datetime.max.time().replace(microsecond=0))
            ) if end_date else start_dt

            with transaction.atomic():
                # Create edition
                edition = Edition.objects.create(
                    title=name,
                    description=f"Edición histórica importada desde Demozoo. {ed_data.get('location', '')}",
                    uploaded_by=admin_user,
                    start_date=start_dt,
                    end_date=end_dt,
                    public=True,
                    open_to_upload=False,
                    open_to_update=False,
                    productions_public=True,
                    auto_approve_productions=True,
                )
                stats["editions_created"] += 1
                self.stdout.write(f"  Created edition: {edition.title} (ID: {edition.id})")

                for comp_data in ed_data["competitions"]:
                    comp_name = comp_data["name"]

                    # Get or create compo
                    compo, created = Compo.objects.get_or_create(
                        name=comp_name,
                        defaults={
                            "description": comp_name,
                            "created_by": admin_user,
                        },
                    )
                    if created:
                        stats["compos_created"] += 1
                    else:
                        stats["compos_reused"] += 1

                    # Create HasCompo link
                    shown_date = self.parse_date(comp_data.get("shown_date"))
                    hascompo_start = timezone.make_aware(
                        datetime.combine(shown_date or start_date or date.today(), datetime.min.time())
                    )

                    HasCompo.objects.get_or_create(
                        edition=edition,
                        compo=compo,
                        defaults={
                            "start": hascompo_start,
                            "show_authors_on_slide": True,
                            "open_to_upload": False,
                            "open_to_update": False,
                            "created_by": admin_user,
                        },
                    )
                    stats["hascompos_created"] += 1

                    # Create productions
                    for prod_data in comp_data["productions"]:
                        authors = ", ".join(prod_data.get("authors", [])) or "Unknown"
                        platform = self.map_platform(prod_data.get("platforms", []))
                        release_date = self.parse_date(prod_data.get("release_date"))
                        demozoo_id = prod_data.get("demozoo_id")

                        position = prod_data.get("position")
                        score = prod_data.get("score")

                        production = Production.objects.create(
                            title=prod_data.get("title", "Untitled"),
                            authors=authors,
                            description="",
                            uploaded_by=admin_user,
                            edition=edition,
                            compo=compo,
                            platform=platform,
                            release_date=release_date,
                            youtube_url=prod_data.get("youtube_url") or "",
                            demozoo_url=f"https://demozoo.org/productions/{demozoo_id}/" if demozoo_id else "",
                            pouet_url=prod_data.get("pouet_url") or "",
                            scene_org_url=prod_data.get("scene_org_url") or "",
                            status="approved",
                            ranking_position=position if position else None,
                            ranking_score=str(score) if score else "",
                        )
                        stats["productions_created"] += 1

                        # Download screenshot
                        if download_screenshots and prod_data.get("screenshots"):
                            shot_url = prod_data["screenshots"][0].get("standard_url") or prod_data["screenshots"][0].get("original_url")
                            if shot_url:
                                result = self.download_screenshot(shot_url)
                                if result:
                                    filename, content = result
                                    path = f"productions/screenshots/{edition.id}/{production.id}/{filename}"
                                    production.screenshot.save(path, ContentFile(content), save=True)
                                    stats["screenshots_downloaded"] += 1

                    self.stdout.write(f"  - {comp_name}: {len(comp_data['productions'])} productions")

        # Summary
        self.stdout.write(f"\n{'='*50}")
        self.stdout.write(self.style.SUCCESS("Import complete:"))
        for key, val in stats.items():
            self.stdout.write(f"  {key}: {val}")
