# Generated by Django 5.2.7 on 2025-10-26 20:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('is_used', models.BooleanField(default=False, verbose_name='Usado')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de uso')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_codes', to='compos.edition', verbose_name='Edición')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_codes', to=settings.AUTH_USER_MODEL, verbose_name='Usado por')),
            ],
            options={
                'verbose_name': 'Código de Asistencia',
                'verbose_name_plural': 'Códigos de Asistencia',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='VotingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('voting_mode', models.CharField(choices=[('public', 'Votación Pública 100%'), ('jury', 'Votación por Jurado 100%'), ('mixed', 'Modalidad Mixta (Público + Jurado)')], default='public', max_length=10, verbose_name='Modalidad de votación')),
                ('public_weight', models.PositiveIntegerField(default=100, help_text='Porcentaje de peso de la votación pública (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Peso votación pública (%)')),
                ('jury_weight', models.PositiveIntegerField(default=0, help_text='Porcentaje de peso de la votación del jurado (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Peso votación jurado (%)')),
                ('access_mode', models.CharField(choices=[('open', 'Abierta por Tiempo'), ('code', 'Código de Asistencia'), ('manual', 'Verificación Manual'), ('checkin', 'Check-in Físico (QR)')], default='open', help_text='Cómo se controla quién puede votar', max_length=10, verbose_name='Modo de acceso')),
                ('results_published', models.BooleanField(default=False, verbose_name='Resultados publicados')),
                ('results_published_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('show_partial_results', models.BooleanField(default=False, help_text='Permitir ver resultados antes del cierre de votación', verbose_name='Mostrar resultados parciales')),
                ('edition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voting_config', to='compos.edition')),
            ],
            options={
                'verbose_name': 'Configuración de Votación',
                'verbose_name_plural': 'Configuraciones de Votación',
            },
        ),
        migrations.CreateModel(
            name='VotingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('start_date', models.DateTimeField(verbose_name='Inicio de votación')),
                ('end_date', models.DateTimeField(verbose_name='Fin de votación')),
                ('is_active', models.BooleanField(default=True)),
                ('compo', models.ForeignKey(blank=True, help_text='Dejar vacío para aplicar a todas las compos', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voting_periods', to='compos.compo', verbose_name='Competición')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_periods', to='compos.edition', verbose_name='Edición')),
            ],
            options={
                'verbose_name': 'Período de Votación',
                'verbose_name_plural': 'Períodos de Votación',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AttendeeVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de verificación')),
                ('verification_method', models.CharField(choices=[('manual', 'Verificación Manual'), ('code', 'Código de Asistencia'), ('checkin', 'Check-in QR')], default='manual', max_length=20, verbose_name='Método de verificación')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_attendees', to='compos.edition', verbose_name='Edición')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendee_verifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_made', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por')),
            ],
            options={
                'verbose_name': 'Verificación de Asistente',
                'verbose_name_plural': 'Verificaciones de Asistentes',
                'unique_together': {('user', 'edition')},
            },
        ),
        migrations.CreateModel(
            name='JuryMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('notes', models.TextField(blank=True, help_text='Información adicional sobre el miembro del jurado', verbose_name='Notas')),
                ('compos', models.ManyToManyField(blank=True, help_text='Compos en las que puede votar. Vacío = todas las compos', related_name='jury_members', to='compos.compo', verbose_name='Competiciones')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_members', to='compos.edition', verbose_name='Edición')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Miembro del Jurado',
                'verbose_name_plural': 'Miembros del Jurado',
                'unique_together': {('user', 'edition')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Puntuación')),
                ('comment', models.TextField(blank=True, max_length=500, verbose_name='Comentario')),
                ('is_jury_vote', models.BooleanField(default=False, help_text='Indica si este voto es de un miembro del jurado', verbose_name='Voto de jurado')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='compos.production', verbose_name='Producción')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Voto',
                'verbose_name_plural': 'Votos',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['production', 'is_jury_vote'], name='compos_vote_product_bd05d5_idx')],
                'unique_together': {('user', 'production')},
            },
        ),
    ]
