# Generated by Django 5.2.7 on 2026-01-11 12:28

import django.db.models.deletion
import dpms.compos.models.gallery
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compos', '0002_attendancecode_votingconfiguration_votingperiod_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('original_filename', models.CharField(blank=True, editable=False, max_length=255)),
                ('image', models.ImageField(max_length=255, upload_to=dpms.compos.models.gallery.gallery_image_upload_to, verbose_name='Image')),
                ('thumbnail', models.ImageField(blank=True, max_length=255, null=True, upload_to='gallery/thumbnails/', verbose_name='Thumbnail')),
                ('public', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('edition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='compos.edition')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['-created'],
            },
        ),
    ]
