# Generated by Django 5.2.7 on 2026-01-11 17:05

import dpms.compos.models.edition
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compos', '0003_add_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=dpms.compos.models.edition.edition_logo_upload_to, verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='edition',
            name='poster',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=dpms.compos.models.edition.edition_poster_upload_to, verbose_name='Poster'),
        ),
    ]
