# Generated by Django 5.2.7 on 2026-01-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compos', '0004_add_logo_poster_to_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='logo_border_color',
            field=models.CharField(default='#FFA500', help_text='Hex color for logo border/glow (e.g., #FFA500)', max_length=7, verbose_name='Logo Border Color'),
        ),
        migrations.AddField(
            model_name='edition',
            name='logo_border_width',
            field=models.PositiveIntegerField(default=0, help_text='Border width in pixels (0 = no border)', verbose_name='Logo Border Width'),
        ),
    ]
