# Generated by Django 5.2.7 on 2026-01-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compos', '0005_add_logo_border_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='productions_public',
            field=models.BooleanField(default=False, help_text='If False, users can only see their own productions. Enable after voting to publish all productions.', verbose_name='Productions Public'),
        ),
    ]
