# Generated by Django 5.2.7 on 2026-01-11 21:29

import dpms.compos.models.sponsors
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compos', '0006_add_productions_public_to_edition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, max_length=255, null=True, upload_to=dpms.compos.models.sponsors.sponsor_logo_upload_to, verbose_name='Logo')),
                ('url', models.URLField(blank=True, help_text="Sponsor's website URL", max_length=500, null=True, verbose_name='Website URL')),
                ('description', models.TextField(blank=True, help_text='Optional description of the sponsor', null=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which sponsors are displayed (lower = first)')),
                ('editions', models.ManyToManyField(blank=True, help_text='Editions this sponsor is associated with', related_name='sponsors', to='compos.edition')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
