# Generated by Django 5.2.7 on 2026-01-25 14:30

import django.db.models.deletion
import dpms.compos.models.stagerunner
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compos', '0007_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageRunnerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('default_background_effect', models.CharField(choices=[('hyperspace', 'Hyperspace'), ('wave', 'Wave'), ('energy-grid', 'Energy Grid'), ('tron-grid', 'Tron Grid'), ('none', 'None')], default='hyperspace', help_text='Default background effect for all slides', max_length=20)),
                ('canvas_width', models.PositiveIntegerField(default=1920, help_text='Canvas width in pixels')),
                ('canvas_height', models.PositiveIntegerField(default=1080, help_text='Canvas height in pixels')),
                ('auto_advance_interval', models.PositiveIntegerField(default=5000, help_text='Interval in ms for auto-advancing slides')),
                ('edition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stagerunner_config', to='compos.edition')),
            ],
            options={
                'verbose_name': 'StageRunner Config',
                'verbose_name_plural': 'StageRunner Configs',
            },
        ),
        migrations.CreateModel(
            name='StageSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('name', models.CharField(help_text='Name of this slide for identification', max_length=255)),
                ('slide_type', models.CharField(choices=[('custom', 'Custom Layout'), ('idle', 'Idle/Waiting'), ('countdown', 'Countdown'), ('production_list', 'Production List'), ('production_show', 'Production Show'), ('results', 'Results')], default='custom', max_length=20)),
                ('background_effect', models.CharField(choices=[('hyperspace', 'Hyperspace'), ('wave', 'Wave'), ('energy-grid', 'Energy Grid'), ('tron-grid', 'Tron Grid'), ('none', 'None'), ('inherit', 'Use Default')], default='inherit', max_length=20)),
                ('background_image', models.ImageField(blank=True, help_text='Optional background image (overlays the effect)', null=True, upload_to=dpms.compos.models.stagerunner.stagerunner_background_upload_to)),
                ('background_color', models.CharField(default='#000000', help_text='Background color in hex format', max_length=7)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which slides are displayed')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duration in ms, 0=manual advance')),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='compos.stagerunnerconfig')),
                ('has_compo', models.ForeignKey(blank=True, help_text='For countdown/list/results screens', null=True, on_delete=django.db.models.deletion.SET_NULL, to='compos.hascompo')),
            ],
            options={
                'ordering': ['display_order', 'created'],
            },
        ),
        migrations.CreateModel(
            name='StageControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('current_production_index', models.PositiveIntegerField(default=0, help_text='Current production index in slideshow')),
                ('is_playing', models.BooleanField(default=False, help_text='Whether auto-advance is active')),
                ('countdown_target', models.DateTimeField(blank=True, help_text='Target datetime for countdown', null=True)),
                ('current_production', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='compos.production')),
                ('config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='control', to='compos.stagerunnerconfig')),
                ('current_slide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='compos.stageslide')),
            ],
            options={
                'verbose_name': 'Stage Control',
                'verbose_name_plural': 'Stage Controls',
            },
        ),
        migrations.CreateModel(
            name='SlideElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('element_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('scrolling_text', 'Scrolling Text'), ('clock', 'Clock'), ('countdown', 'Countdown Timer'), ('production_info', 'Production Info'), ('sponsor_bar', 'Sponsor Bar')], max_length=20)),
                ('name', models.CharField(blank=True, help_text='Optional name for this element', max_length=100)),
                ('x', models.FloatField(default=0, help_text='X position as percentage (0-100)')),
                ('y', models.FloatField(default=0, help_text='Y position as percentage (0-100)')),
                ('width', models.FloatField(default=20, help_text='Width as percentage (0-100)')),
                ('height', models.FloatField(default=10, help_text='Height as percentage (0-100)')),
                ('rotation', models.FloatField(default=0, help_text='Rotation in degrees')),
                ('z_index', models.PositiveIntegerField(default=0, help_text='Stacking order (higher = on top)')),
                ('content', models.TextField(blank=True, help_text='Text content or URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to=dpms.compos.models.stagerunner.stagerunner_element_image_upload_to)),
                ('video', models.FileField(blank=True, null=True, upload_to=dpms.compos.models.stagerunner.stagerunner_video_upload_to)),
                ('styles', models.JSONField(blank=True, default=dict, help_text='CSS-like styles as JSON')),
                ('enter_transition', models.CharField(choices=[('none', 'None'), ('fade', 'Fade'), ('slide_left', 'Slide from Left'), ('slide_right', 'Slide from Right'), ('slide_up', 'Slide from Bottom'), ('slide_down', 'Slide from Top'), ('zoom', 'Zoom In'), ('bounce', 'Bounce')], default='fade', max_length=20)),
                ('exit_transition', models.CharField(choices=[('none', 'None'), ('fade', 'Fade'), ('slide_left', 'Slide from Left'), ('slide_right', 'Slide from Right'), ('slide_up', 'Slide from Bottom'), ('slide_down', 'Slide from Top'), ('zoom', 'Zoom In'), ('bounce', 'Bounce')], default='fade', max_length=20)),
                ('enter_duration', models.PositiveIntegerField(default=500, help_text='Enter transition duration in ms')),
                ('exit_duration', models.PositiveIntegerField(default=500, help_text='Exit transition duration in ms')),
                ('enter_delay', models.PositiveIntegerField(default=0, help_text='Delay before entering in ms')),
                ('is_visible', models.BooleanField(default=True)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='compos.stageslide')),
            ],
            options={
                'ordering': ['z_index', 'created'],
            },
        ),
    ]
