# Generated by Django 5.2.7 on 2026-01-25 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compos', '0008_stagerunner'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideelement',
            name='list_max_items',
            field=models.PositiveIntegerField(default=10, help_text='Maximum items to show in lists'),
        ),
        migrations.AddField(
            model_name='slideelement',
            name='list_show_position',
            field=models.BooleanField(default=True, help_text='Show position number'),
        ),
        migrations.AddField(
            model_name='slideelement',
            name='list_show_score',
            field=models.BooleanField(default=False, help_text='Show score (results only)'),
        ),
        migrations.AddField(
            model_name='slideelement',
            name='podium_show_points',
            field=models.BooleanField(default=True, help_text='Show points on podium'),
        ),
        migrations.AddField(
            model_name='slideelement',
            name='video_mode',
            field=models.CharField(choices=[('inline', 'Inline (plays in slide)'), ('external', 'External (info only, video separate)'), ('none', 'No video')], default='inline', help_text='How to handle production video', max_length=10),
        ),
        migrations.AddField(
            model_name='stagecontrol',
            name='command',
            field=models.CharField(blank=True, choices=[('', 'None'), ('next', 'Next Slide'), ('prev', 'Previous Slide'), ('play', 'Play'), ('pause', 'Pause'), ('next_production', 'Next Production'), ('prev_production', 'Previous Production'), ('reveal_next', 'Reveal Next Position'), ('reveal_all', 'Reveal All Positions'), ('reset_reveal', 'Reset Revelation')], default='', help_text='Last command sent', max_length=20),
        ),
        migrations.AddField(
            model_name='stagecontrol',
            name='command_timestamp',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp for sync'),
        ),
        migrations.AddField(
            model_name='stagecontrol',
            name='current_slide_index',
            field=models.PositiveIntegerField(default=0, help_text='Current slide index in presentation'),
        ),
        migrations.AddField(
            model_name='stagecontrol',
            name='is_video_playing',
            field=models.BooleanField(default=False, help_text='Whether a video is currently playing'),
        ),
        migrations.AddField(
            model_name='stagecontrol',
            name='revealed_positions',
            field=models.PositiveIntegerField(default=0, help_text='Number of positions revealed (counts down from end)'),
        ),
        migrations.AddField(
            model_name='stageslide',
            name='auto_advance_productions',
            field=models.BooleanField(default=False, help_text='Automatically advance between productions'),
        ),
        migrations.AddField(
            model_name='stageslide',
            name='countdown_label',
            field=models.CharField(blank=True, help_text="Label for countdown (e.g., 'Demo Compo starts in')", max_length=255),
        ),
        migrations.AddField(
            model_name='stageslide',
            name='countdown_target',
            field=models.DateTimeField(blank=True, help_text='Target datetime for countdown', null=True),
        ),
        migrations.AddField(
            model_name='stageslide',
            name='production',
            field=models.ForeignKey(blank=True, help_text="For slide type 'production_show'", null=True, on_delete=django.db.models.deletion.SET_NULL, to='compos.production'),
        ),
        migrations.AddField(
            model_name='stageslide',
            name='production_display_time',
            field=models.PositiveIntegerField(default=10000, help_text='Time per production in ms (if auto-advance)'),
        ),
        migrations.AlterField(
            model_name='slideelement',
            name='element_type',
            field=models.CharField(choices=[('text', 'Static Text'), ('image', 'Image'), ('video', 'Video'), ('scrolling_text', 'Scrolling Text'), ('clock', 'Clock'), ('countdown', 'Countdown Timer'), ('compo_name', 'Compo Name'), ('compo_description', 'Compo Description'), ('production_number', 'Production Number'), ('production_title', 'Production Title'), ('production_authors', 'Production Authors'), ('production_video', 'Production Video/Preview'), ('production_list', 'Production List'), ('results_table', 'Results Table'), ('podium', 'Podium Display'), ('sponsor_bar', 'Sponsor Bar'), ('sponsor_grid', 'Sponsor Grid'), ('edition_logo', 'Edition Logo'), ('edition_poster', 'Edition Poster')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stagerunnerconfig',
            name='default_background_effect',
            field=models.CharField(choices=[('hyperspace', 'Hyperspace'), ('wave', 'Wave'), ('energy-grid', 'Energy Grid'), ('tron-grid', 'Tron Grid'), ('wuhu-boxes', 'Wuhu Boxes'), ('wuhu-boxes-fire', 'Wuhu Boxes Fire'), ('wuhu-boxes-purple', 'Wuhu Boxes Purple'), ('floating-spheres', 'Floating Spheres'), ('spinning-toroids', 'Spinning Toroids'), ('crystal-pyramids', 'Crystal Pyramids'), ('infinite-tunnel', 'Infinite Tunnel'), ('none', 'None')], default='hyperspace', help_text='Default background effect for all slides', max_length=20),
        ),
        migrations.AlterField(
            model_name='stageslide',
            name='background_effect',
            field=models.CharField(choices=[('hyperspace', 'Hyperspace'), ('wave', 'Wave'), ('energy-grid', 'Energy Grid'), ('tron-grid', 'Tron Grid'), ('wuhu-boxes', 'Wuhu Boxes'), ('wuhu-boxes-fire', 'Wuhu Boxes Fire'), ('wuhu-boxes-purple', 'Wuhu Boxes Purple'), ('floating-spheres', 'Floating Spheres'), ('spinning-toroids', 'Spinning Toroids'), ('crystal-pyramids', 'Crystal Pyramids'), ('infinite-tunnel', 'Infinite Tunnel'), ('none', 'None'), ('inherit', 'Use Default')], default='inherit', max_length=20),
        ),
        migrations.AlterField(
            model_name='stageslide',
            name='has_compo',
            field=models.ForeignKey(blank=True, help_text='For compo/results screens', null=True, on_delete=django.db.models.deletion.SET_NULL, to='compos.hascompo'),
        ),
        migrations.AlterField(
            model_name='stageslide',
            name='slide_type',
            field=models.CharField(choices=[('custom', 'Custom Layout'), ('idle', 'Idle/Waiting'), ('compo_intro', 'Compo Introduction'), ('production_list', 'Production List'), ('production_show', 'Single Production'), ('results_live', 'Live Results'), ('results_final', 'Final Results'), ('podium', 'Podium/Top 3'), ('countdown', 'Countdown'), ('sponsors', 'Sponsors Showcase'), ('video', 'Video Player')], default='custom', max_length=20),
        ),
        migrations.CreateModel(
            name='StagePresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('name', models.CharField(max_length=255)),
                ('presentation_type', models.CharField(choices=[('idle', 'Idle/All Day'), ('compo', 'Compo Presentation'), ('awards', 'Awards Ceremony'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='compos.stagerunnerconfig')),
                ('has_compo', models.ForeignKey(blank=True, help_text="Associated compo (for 'compo' or 'awards' types)", null=True, on_delete=django.db.models.deletion.SET_NULL, to='compos.hascompo')),
            ],
            options={
                'verbose_name': 'Stage Presentation',
                'verbose_name_plural': 'Stage Presentations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PresentationSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_presentations', to='compos.stageslide')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_slides', to='compos.stagepresentation')),
            ],
            options={
                'verbose_name': 'Presentation Slide',
                'verbose_name_plural': 'Presentation Slides',
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='stagecontrol',
            name='current_presentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='compos.stagepresentation'),
        ),
    ]
