# Generated by Django 5.2.7 on 2026-03-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compos', '0009_stagerunner_presentations'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when the edition ends', null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='edition',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when the edition starts', null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='slideelement',
            name='element_type',
            field=models.CharField(choices=[('text', 'Static Text'), ('image', 'Image'), ('video', 'Video'), ('scrolling_text', 'Scrolling Text'), ('clock', 'Clock'), ('countdown', 'Countdown Timer'), ('shape', 'Shape'), ('compo_name', 'Compo Name'), ('compo_description', 'Compo Description'), ('production_number', 'Production Number'), ('production_title', 'Production Title'), ('production_authors', 'Production Authors'), ('production_video', 'Production Video/Preview'), ('production_list', 'Production List'), ('results_table', 'Results Table'), ('podium', 'Podium Display'), ('sponsor_bar', 'Sponsor Bar'), ('sponsor_grid', 'Sponsor Grid'), ('edition_logo', 'Edition Logo'), ('edition_poster', 'Edition Poster')], max_length=20),
        ),
    ]
