# Generated by Django 5.2.7 on 2026-04-03 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compos', '0010_add_start_end_date_to_edition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='auto_approve_productions',
            field=models.BooleanField(default=True, help_text='Automatically approve new productions on submission. If disabled, productions require manual admin approval.', verbose_name='Auto-approve Productions'),
        ),
        migrations.AddField(
            model_name='production',
            name='rejection_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='production',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('technical', 'No cumple requisitos técnicos'), ('inappropriate', 'Contenido inapropiado'), ('wrong_compo', 'Compo incorrecta'), ('duplicate', 'Duplicado'), ('other', 'Otro')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='production',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_productions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='production',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=20),
        ),
    ]
