# Generated by Django 5.2.7 on 2026-04-03 09:29

import dpms.compos.models.productions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compos', '0012_update_compo_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='demozoo_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='production',
            name='platform',
            field=models.CharField(blank=True, choices=[('amiga_ocs', 'Amiga OCS'), ('amiga_aga', 'Amiga AGA'), ('pc', 'PC'), ('c64', 'Commodore 64'), ('atari_st', 'Atari ST'), ('zx_spectrum', 'ZX Spectrum'), ('msx', 'MSX'), ('amstrad_cpc', 'Amstrad CPC'), ('snes', 'SNES'), ('megadrive', 'Mega Drive'), ('gameboy', 'Game Boy'), ('arduino', 'Arduino'), ('web', 'Web/Browser'), ('multiplatform', 'Multiplataforma'), ('other', 'Otra')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='production',
            name='pouet_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='production',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='scene_org_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='production',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to=dpms.compos.models.productions.production_screenshot_path),
        ),
        migrations.AddField(
            model_name='production',
            name='youtube_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
