# Generated by Django 5.2.7 on 2026-04-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compos', '0014_populate_production_details_from_demozoo'),
    ]

    operations = [
        migrations.AddField(
            model_name='compo',
            name='rules',
            field=models.TextField(blank=True, default=''),
        ),
    ]
