# Generated by Django 5.2.7 on 2026-04-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compos', '0016_populate_compo_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='contact_email',
            field=models.EmailField(blank=True, default='', help_text='Email address where contact form messages will be sent', max_length=254, verbose_name='Contact Email'),
        ),
        migrations.AddField(
            model_name='edition',
            name='contact_form_enabled',
            field=models.BooleanField(default=False, help_text='Enable the public contact form for this edition', verbose_name='Contact Form Enabled'),
        ),
        migrations.AddField(
            model_name='edition',
            name='contact_info',
            field=models.TextField(blank=True, default='', help_text='Contact information in markdown format (social media, email, Telegram, etc.)', verbose_name='Contact Info'),
        ),
        migrations.AddField(
            model_name='edition',
            name='travel_info',
            field=models.TextField(blank=True, default='', help_text='How to get there: venue address, airports, trains, buses, parking, accommodation (markdown)', verbose_name='Travel Info'),
        ),
    ]
