# Generated by Django 5.2.7 on 2026-04-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compos', '0018_populate_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='compo',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='compo',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='compo',
            name='rules_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='compo',
            name='rules_es',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='contact_info_en',
            field=models.TextField(blank=True, default='', help_text='Contact information in markdown format (social media, email, Telegram, etc.)', null=True, verbose_name='Contact Info'),
        ),
        migrations.AddField(
            model_name='edition',
            name='contact_info_es',
            field=models.TextField(blank=True, default='', help_text='Contact information in markdown format (social media, email, Telegram, etc.)', null=True, verbose_name='Contact Info'),
        ),
        migrations.AddField(
            model_name='edition',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='travel_info_en',
            field=models.TextField(blank=True, default='', help_text='How to get there: venue address, airports, trains, buses, parking, accommodation (markdown)', null=True, verbose_name='Travel Info'),
        ),
        migrations.AddField(
            model_name='edition',
            name='travel_info_es',
            field=models.TextField(blank=True, default='', help_text='How to get there: venue address, airports, trains, buses, parking, accommodation (markdown)', null=True, verbose_name='Travel Info'),
        ),
    ]
