# Generated by Django 5.2.11 on 2026-04-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compos', '0022_translate_edition_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
