# Generated by Django 5.2.11 on 2026-04-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compos', '0023_allow_blank_file_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
