# Generated by Django 5.2.11 on 2026-04-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compos', '0024_allow_blank_production_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingconfiguration',
            name='show_score_breakdown',
            field=models.BooleanField(default=False, help_text='Mostrar el detalle de votos públicos y de jurado por separado', verbose_name='Mostrar desglose de puntuación'),
        ),
    ]
