# Generated by Django 5.2.11 on 2026-04-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compos', '0025_add_show_score_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='ranking_position',
            field=models.PositiveIntegerField(blank=True, help_text='Position in competition results (from historical data)', null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='ranking_score',
            field=models.CharField(blank=True, default='', help_text='Score in competition results (from historical data)', max_length=50),
        ),
    ]
