# Generated by Django 5.2.11 on 2026-04-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compos', '0026_add_ranking_fields_to_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='schedule',
            field=models.TextField(blank=True, default='', help_text='Event schedule/programme in markdown format', verbose_name='Schedule'),
        ),
        migrations.AddField(
            model_name='edition',
            name='what_to_bring',
            field=models.TextField(blank=True, default='', help_text='What attendees should bring and basic conduct rules (markdown)', verbose_name='What to Bring'),
        ),
    ]
