# Generated by Django 5.2.11 on 2026-04-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compos', '0028_populate_what_to_bring_posadas2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='compo',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='compo',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='compo',
            name='description_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='compo',
            name='rules_de',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='compo',
            name='rules_fr',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='compo',
            name='rules_pt',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='contact_info_de',
            field=models.TextField(blank=True, default='', help_text='Contact information in markdown format (social media, email, Telegram, etc.)', null=True, verbose_name='Contact Info'),
        ),
        migrations.AddField(
            model_name='edition',
            name='contact_info_fr',
            field=models.TextField(blank=True, default='', help_text='Contact information in markdown format (social media, email, Telegram, etc.)', null=True, verbose_name='Contact Info'),
        ),
        migrations.AddField(
            model_name='edition',
            name='contact_info_pt',
            field=models.TextField(blank=True, default='', help_text='Contact information in markdown format (social media, email, Telegram, etc.)', null=True, verbose_name='Contact Info'),
        ),
        migrations.AddField(
            model_name='edition',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='description_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='travel_info_de',
            field=models.TextField(blank=True, default='', help_text='How to get there: venue address, airports, trains, buses, parking, accommodation (markdown)', null=True, verbose_name='Travel Info'),
        ),
        migrations.AddField(
            model_name='edition',
            name='travel_info_fr',
            field=models.TextField(blank=True, default='', help_text='How to get there: venue address, airports, trains, buses, parking, accommodation (markdown)', null=True, verbose_name='Travel Info'),
        ),
        migrations.AddField(
            model_name='edition',
            name='travel_info_pt',
            field=models.TextField(blank=True, default='', help_text='How to get there: venue address, airports, trains, buses, parking, accommodation (markdown)', null=True, verbose_name='Travel Info'),
        ),
    ]
