# Generated by Django 5.2.11 on 2026-04-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compos', '0029_compo_description_de_compo_description_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='schedule_de',
            field=models.TextField(blank=True, default='', help_text='Event schedule/programme in markdown format', null=True, verbose_name='Schedule'),
        ),
        migrations.AddField(
            model_name='edition',
            name='schedule_en',
            field=models.TextField(blank=True, default='', help_text='Event schedule/programme in markdown format', null=True, verbose_name='Schedule'),
        ),
        migrations.AddField(
            model_name='edition',
            name='schedule_es',
            field=models.TextField(blank=True, default='', help_text='Event schedule/programme in markdown format', null=True, verbose_name='Schedule'),
        ),
        migrations.AddField(
            model_name='edition',
            name='schedule_fr',
            field=models.TextField(blank=True, default='', help_text='Event schedule/programme in markdown format', null=True, verbose_name='Schedule'),
        ),
        migrations.AddField(
            model_name='edition',
            name='schedule_pt',
            field=models.TextField(blank=True, default='', help_text='Event schedule/programme in markdown format', null=True, verbose_name='Schedule'),
        ),
        migrations.AddField(
            model_name='edition',
            name='what_to_bring_de',
            field=models.TextField(blank=True, default='', help_text='What attendees should bring and basic conduct rules (markdown)', null=True, verbose_name='What to Bring'),
        ),
        migrations.AddField(
            model_name='edition',
            name='what_to_bring_en',
            field=models.TextField(blank=True, default='', help_text='What attendees should bring and basic conduct rules (markdown)', null=True, verbose_name='What to Bring'),
        ),
        migrations.AddField(
            model_name='edition',
            name='what_to_bring_es',
            field=models.TextField(blank=True, default='', help_text='What attendees should bring and basic conduct rules (markdown)', null=True, verbose_name='What to Bring'),
        ),
        migrations.AddField(
            model_name='edition',
            name='what_to_bring_fr',
            field=models.TextField(blank=True, default='', help_text='What attendees should bring and basic conduct rules (markdown)', null=True, verbose_name='What to Bring'),
        ),
        migrations.AddField(
            model_name='edition',
            name='what_to_bring_pt',
            field=models.TextField(blank=True, default='', help_text='What attendees should bring and basic conduct rules (markdown)', null=True, verbose_name='What to Bring'),
        ),
    ]
