# Generated by Django 5.2.11 on 2026-04-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compos', '0031_translate_posadas_party_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='compo',
            name='description_fi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='compo',
            name='rules_fi',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='contact_info_fi',
            field=models.TextField(blank=True, default='', help_text='Contact information in markdown format (social media, email, Telegram, etc.)', null=True, verbose_name='Contact Info'),
        ),
        migrations.AddField(
            model_name='edition',
            name='description_fi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='schedule_fi',
            field=models.TextField(blank=True, default='', help_text='Event schedule/programme in markdown format', null=True, verbose_name='Schedule'),
        ),
        migrations.AddField(
            model_name='edition',
            name='travel_info_fi',
            field=models.TextField(blank=True, default='', help_text='How to get there: venue address, airports, trains, buses, parking, accommodation (markdown)', null=True, verbose_name='Travel Info'),
        ),
        migrations.AddField(
            model_name='edition',
            name='what_to_bring_fi',
            field=models.TextField(blank=True, default='', help_text='What attendees should bring and basic conduct rules (markdown)', null=True, verbose_name='What to Bring'),
        ),
    ]
