# Generated by Django 5.2.11 on 2026-04-19 10:15

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compos', '0033_translate_posadas_party_2026_fi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='attendance_count_public',
            field=models.BooleanField(default=False, help_text='Publish the confirmed-attendance counter on the landing page.', verbose_name='Attendance Count Public'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified at')),
                ('equipment', models.TextField(blank=True, default='', help_text='Descripción libre del equipo/material que el asistente traerá.', verbose_name='Equipo que trae')),
                ('sleeps_at', models.CharField(choices=[('venue', 'En la party'), ('external', 'Fuera')], default='venue', max_length=10, verbose_name='Dónde duerme')),
                ('days', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, default=list, help_text='Lista de fechas dentro del rango de la edición que el asistente confirma.', size=None, verbose_name='Días que asistirá')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='compos.edition', verbose_name='Edición')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ('-created',),
                'constraints': [models.UniqueConstraint(fields=('user', 'edition'), name='unique_attendance_per_user_and_edition')],
            },
        ),
    ]
