# Generated by Django 5.2.11 on 2026-04-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='extra_information',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
